### ISSUE TITLE
Rendering errors in Android Studio 0.8.9 (beta)

### ISSUE THREAD

**Issue by vickychijwani** [Pkmmte/CircularImageView#12]
I get the following errors in the Preview tab when I add a `CircularImageView` to an XML layout:

```
Rendering Problems
Missing styles. Is the correct theme chosen for this layout?
Failed to find style 'circularImageViewStyle' in current theme (3 similar errors not shown)
```

I'm guessing it's got something to do with [these lines in res/values/attrs.xml](https://github.com/Pkmmte/CircularImageView/blob/db81021edaa683ba07cf7eff38b06f1fd009fdcb/circularimageview/src/main/res/values/attrs.xml#L25-L27).

**Comment by stephanemaarek** [comment]
Any words on the release of this fix?

**Comment by Mindstormer619** [comment]
I am still having this error on AS v1.1.0

**Comment by jonasborggren** [comment]
Still problem in AS v1.3

**Comment by solraves** [comment]
And even in AS 1.4 RC1

**Comment by henriquedesousa** [comment]
Why was this closed?
