### ISSUE TITLE
Attribute "border_color" has already been defined

### ISSUE THREAD

**Issue by mehrad-rafigh** [Pkmmte/CircularImageView#21]
In combination with the google play services version 6.1.71 I get this error when I add your library as a dependency with gradle.

**Comment by Pkmmte** [comment]
This fix will be included in version 2.0 of the library.
To bypass this issue, you'll now need to prefix attributes with "civ_".

**Comment by mehrad-rafigh** [comment]
Good to know! When will the 2.0 version of this library be available?

**Comment by Pkmmte** [comment]
If all goes well, it should be available in the next 72 hours.
No guarantees, however.
