### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by FlorentAnders** [Pkmmte/CircularImageView#22]
I'm getting a NullPointerException at createScaledBitmap when I'm scrolling down in my ListView to a certain item. I'm using Picasso, this is my code to set the image into the CircularImageDrawable:

Picasso.with(activity).load(artist.getImage()).into(image);

**Comment by rahulfhp** [comment]
what do you mean by your own picasso code ? I am having the same issue using Glide .

**Comment by abspatel7** [comment]
can u explaion your proble in detail..
I'll try to solve that if possible

**Comment by asadwaheed1** [comment]
I am also having same issue using glide
