### ISSUE TITLE
Stackoverflow if image is loaded from network

### ISSUE THREAD

**Issue by anti43** [Pkmmte/CircularImageView#23]
android.widget.ImageView.invalidateDrawable (ImageView.java:190)
android.graphics.drawable.Drawable.invalidateSelf (Drawable.java:338)
com.koushikdutta.ion.IonDrawable.draw (IonDrawable.java:688)
com.pkmmte.view.CircularImageView.drawableToBitmap (CircularImageView.java:331)
com.pkmmte.view.CircularImageView.invalidate (CircularImageView.java:260)
android.widget.ImageView.invalidateDrawable (ImageView.java:190)

**Comment by Pkmmte** [comment]
This has been fixed and will be included in version 2.0 of the library.

**Comment by phileo** [comment]
Any estimates as to when v2.0 will be released to maven ?

**Comment by Pkmmte** [comment]
I'll be honest and say the reason I haven't yet pushed it to Maven is due to me having forgot my key password. I'll release the moment I find it..

**Comment by rahulfhp** [comment]
is version 2 released ? Need it badly .
