### ISSUE TITLE
Rendering Problems: Android Studio 0.8.1 (Beta) 

### ISSUE THREAD

**Issue by cotzanium17** [Pkmmte/CircularImageView#26]
Im getting the following error when i try to edit view the layout. However on the emulator and test device its displaying properly.  I also cannot set the app:border, etc properties on the xml.
![screen shot 2014-12-05 at 12 17 36 pm](https://cloud.githubusercontent.com/assets/4740267/5314215/e118db4a-7c78-11e4-8507-76f6a0392a3e.png)

I have: compile 'com.pkmmte.view:circularimageview:1.1' in my gradle file

**Comment by Pkmmte** [comment]
This has been fixed and will be included in version 2.0 of the library.
